CREATE TABLE Food (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  calories_per_gram DECIMAL(6,3) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DayRecord (
   id INT AUTO_INCREMENT PRIMARY KEY,
   date DATE NOT NULL UNIQUE
);

CREATE TABLE Meal (
  id INT AUTO_INCREMENT PRIMARY KEY,
  day_id INT NOT NULL,
  meal_name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (day_id) REFERENCES DayRecord(id) ON DELETE CASCADE
);

CREATE TABLE MealFood (
  id INT AUTO_INCREMENT PRIMARY KEY,
  meal_id INT NOT NULL,
  food_id INT NOT NULL,
  grams DECIMAL(8,2) NOT NULL,
  FOREIGN KEY (meal_id) REFERENCES Meal(id) ON DELETE CASCADE,
  FOREIGN KEY (food_id) REFERENCES Food(id)
);